### ISSUE TITLE
The generated image is black when switching to read the lora weights

### ISSUE THREAD

**Issue by sanbuphy** [Oneflow-Inc/onediff#217]
Hi, I referred to this method (https://github.com/huggingface/diffusers/issues/3064#issuecomment-1514082155) for runtime switching inference of LoRa weights. It works well on Hugging Face's Diffuser, but when I use it in OneFlow diffuser , the first weight switching is fine with no problem, but when I switch for the second time, the generated images all turn black.

**Comment by NicholasKao1029** [comment]
@sanbuphy were you able to move forward with this?

**Comment by strint** [comment]
It has been fixed now:https://github.com/Oneflow-Inc/onediff/blob/main/examples/text_to_image_sdxl_lora.py

Please update to the latest version: https://github.com/Oneflow-Inc/onediff?tab=readme-ov-file#install-from-source
This issue is too old to follow and will be closed. Feel free to reopen it and continue.
